[profile.default]
evm_version = "cancun"
ffi = true
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@uniswap/v4-core/=lib/uniswap-hooks/lib/v4-core/",
    "@uniswap/v4-periphery/=lib/uniswap-hooks/lib/v4-periphery/",
    "v4-core/=lib/uniswap-hooks/lib/v4-core/",
    "v4-periphery/=lib/uniswap-hooks/lib/v4-periphery/",
    "@openzeppelin/uniswap-hooks/=lib/uniswap-hooks/",
    # BEFORE: @openzeppelin/contracts/=lib/uniswap-hooks/lib/v4-core/lib/openzeppelin-contracts/contracts/
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    #             ^
    #  AFTER:     |: This is to allow for the import of AccessControlEnumerable to resolve imports on
    # lib/Algebra/src/core/contracts/AlgebraFactory.sol:import "@openzeppelin/contracts/access/AccessControlEnumerable.sol";
    "hookmate/=lib/hookmate/src/",
    "permit2/=lib/uniswap-hooks/lib/v4-periphery/lib/permit2/",
    "solmate/=lib/uniswap-hooks/lib/v4-core/lib/solmate/",
    # NEW REMAPPINGS INTRODUCED WIH ALGEBRA INTEGRATION
    "@cryptoalgebra/=node_modules/@cryptoalgebra/",
    "Algebra/=lib/Algebra/src/",
    "hardhat/=node_modules/hardhat/",
]


fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
libs = [
    "node_modules",
    "lib",
] #Included node_modules for hardhat-foundry to resolve imports
out = "out"
auto_detect_solc = true
src = "src"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
