[profile.default]
evm_version = "cancun"
ffi = true
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@uniswap/v4-core/=lib/uniswap-hooks/lib/v4-core/",
    "@uniswap/v4-periphery/=lib/uniswap-hooks/lib/v4-periphery/",
    "v4-core/=lib/uniswap-hooks/lib/v4-core/",
    "v4-periphery/=lib/uniswap-hooks/lib/v4-periphery/",
    "@openzeppelin/uniswap-hooks/=lib/uniswap-hooks/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "hookmate/=lib/hookmate/src/",
    "permit2/=lib/uniswap-hooks/lib/v4-periphery/lib/permit2/",
    "solmate/=lib/uniswap-hooks/lib/v4-core/lib/solmate/",
    "@cryptoalgebra/=node_modules/@cryptoalgebra/",
    "Algebra/=lib/Algebra/src/",
    "hardhat/=node_modules/hardhat/",
]


fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
libs = ["node_modules", "lib"]
out = "out"
solc_version = "0.8.28"
src = "src"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
